[package]
name = "reserde"
version = "0.0.0-dev"
authors = ["Tamme Schichler <tamme@schichler.dev>"]
edition = "2018"
publish = false

[features]
default = ["de-json", "ser-json", "de-taml", "de-xml", "ser-xml", "de-yaml", "ser-yaml"]
de-json = ["serde_json", "serde-detach"]
ser-json = ["serde_json"]
de-taml = ["taml", "serde-detach"]
de-xml = ["quick-xml", "serde-detach"]
ser-xml = ["quick-xml"]
de-yaml = ["serde_yaml", "serde-detach"]
ser-yaml = ["serde_yaml"]

[dependencies]
argh = "0.1.3"
quick-xml = { version = "0.18.1", optional = true, features = ["serialize"] }
serde = "1.0.114"
serde-object = { path = "../serde-object" }
serde-detach = { path = "../serde-detach", optional = true }
serde_json = { version = "1.0.57", optional = true } #TODO: Check out features.
serde_yaml = { version = "0.8.13", optional = true }
strum = { version = "0.19.1", features = ["derive"] }
taml = { path = "../taml", optional = true } #TODO: "de" and "ser" features?
wyz = "0.2.0"
